# Downloads updates from Spigot automatically
auto-updater-enabled: true
# Maximum amount of hoppers per chunk
max-hoppers-per-chunk: 5
# Item collection allows hoppers to pick items up from a distance, reducing the amount of hoppers your players need, and in turn, reduces lag
item-collection:
  enabled: true
  # Chunk: Collects items in the same chunk as a hopper
  # Radius: Collects items in a radius around a hopper
  mode: Chunk
  # Radius in which items are collected around a hopper. Only works in radius mode
  radius: 16
  # Determines if radius ignores Y axis distance or not
  ignore-y: false