name: FilteringHoppers
description: Allows you to add a filter to your hoppers for more efficient storage!
main: me.cocolennon.filteringhoppers.Main
version: 1.2.2
author: Cocolennon
api-version: '1.20'
folia-supported: true
commands:
  filteringhoppers:
    description: Check out information about the plugin!
    aliases:
      - fh
permissions:
  filteringhoppers.reload:
    description: Allows user to reload the configuration
  filteringhoppers.set.max-hoppers-per-chunk:
    description: Allows user to set the maximum amount of hoppers per chunk
  filteringhoppers.set.item-collection.enabled:
    description: Allows user to toggle item collection
  filteringhoppers.set.item-collection.mode:
    description: Allows user to set item collection mode
  filteringhoppers.set.item-collection.radius:
    description: Allows user to set item collection radius